"""GitHub PR creation."""

from github_integration.client import get_repo


async def create_test_pr(
    repo_url: str,
    branch: str,
    run_id: str,
    generated_tests: dict[str, str],
    test_results: list[dict],
    coverage_pct: float,
) -> str:
    """Create a branch, commit test files, and open a GitHub PR."""
    repo = get_repo(repo_url)
    base_branch = repo.get_branch(branch)

    # Create new branch
    new_branch = f"test/agent-{run_id[:8]}"
    repo.create_git_ref(
        ref=f"refs/heads/{new_branch}",
        sha=base_branch.commit.sha,
    )

    # Commit each test file
    for source_file, test_content in generated_tests.items():
        test_path = _source_to_test_path(source_file)
        repo.create_file(
            path=test_path,
            message=f"test: add AI-generated tests for {source_file}",
            content=test_content,
            branch=new_branch,
        )

    # Build PR body
    body = _build_pr_body(generated_tests, test_results, coverage_pct, run_id)

    # Open PR
    pr = repo.create_pull(
        title="chore: add AI-generated test suite",
        body=body,
        head=new_branch,
        base=branch,
    )

    return pr.html_url


def _source_to_test_path(source_file: str) -> str:
    """Convert source file path to test file path."""
    if source_file.endswith(".py"):
        name = source_file.rsplit("/", 1)[-1]
        return f"tests/test_{name}"
    else:
        name = source_file.rsplit("/", 1)[-1]
        base, ext = name.rsplit(".", 1)
        return f"tests/{base}.test.{ext}"


def _build_pr_body(
    generated_tests: dict,
    test_results: list[dict],
    coverage_pct: float,
    run_id: str,
) -> str:
    """Build markdown PR description."""
    rows = ""
    for result in test_results:
        rows += (
            f"| {result.get('source_file', '')} "
            f"| {result.get('passed', 0)} "
            f"| {result.get('failed', 0)} "
            f"| {result.get('coverage_pct', 0):.1f}% |\n"
        )

    return f"""## AI-Generated Test Suite

**Agent Run ID:** `{run_id}`
**Overall Coverage:** {coverage_pct:.1f}%

### Files Tested

| Source File | Passed | Failed | Coverage |
|------------|--------|--------|----------|
{rows}

---
*Generated by Autonomous Code Review & Testing Agent*
"""
